name: CI/CD for commons-ts
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 21.6.0
        uses: actions/setup-node@v3
        with:
          node-version: 21.6.0
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run my action
        uses: ./
        with:
          name: "This commons_ts"
          ghToken: ${{ secrets.COMMONS_TS }}
