name: CI/CD for commons-ts
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

  merge-if-success:
    name: Merge if successful
    runs-on: ubuntu-latest
    needs: run-action
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false && success() # Ensure the workflow only runs on PRs and when previous job is successful
    steps:
      - name: Merge Pull Request
        if: github.event_name == 'pull_request' && github.event.pull_request.draft == false && success() # Check that it's a PR and not a draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub provides a default token with sufficient permissions
        run: |
          PR_URL="${{ github.event.pull_request.url }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"

          echo "Merging pull request #${PR_NUMBER}"
          curl -X PUT \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"merge_method":"merge"}' \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/merge"
